version: "3.9"
services:
  resume:
    build: .
    ports:
      - "5001:80"
    networks:
      - db-network
  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - db-network
    depends_on:
      - db
    ports:
      - "8081:8081"
volumes:
  db-data:
    name: db-data
networks:
  db-network:
    name: db-network
