version: "3.9"
services:
  service:
    container_name: resume-service
    build: .
    working_dir: /app
    command: ['yarn', 'dev']
    volumes: 
      - .:/app
    ports:
      - "5001:80"
    networks:
      - db-network
  auth:
    image: djasuar/auth-service:latest
    container_name: auth-service
    command: ['yarn', 'start']
    environment:
      - DATABASE_URL=mongodb://db:27017
      - DATABASE_NAME=auth
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
    ports:
      - "5002:80"
    networks:
      - db-network
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - db-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - db-network
    depends_on:
      - db
    ports:
      - "8081:8081"
volumes:
  db-data:
    name: db-data
networks:
  db-network:
    name: db-network
